# Generated by Django 3.0.8 on 2020-07-23 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.CITIES_CONTINENT_MODEL),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.AlternativeName')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL)),
                ('continents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CONTINENT_MODEL)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_COUNTRY_MODEL)),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.District')),
                ('postal_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.PostalCode')),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Region')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Subregion')),
            ],
        ),
    ]
